# tasks file
---
- ansible.builtin.import_tasks: version-support.yml
  tags:
    - configuration
    - percona-toolkit
    - percona-toolkit-repo-version-support

- ansible.builtin.import_tasks: repository.yml
  tags:
    - configuration
    - percona-toolkit
    - percona-toolkit-repository

- ansible.builtin.import_tasks: install.yml
  tags:
    - configuration
    - percona-toolkit
    - percona-toolkit-install

- ansible.builtin.import_tasks: configure.yml
  tags:
    - configuration
    - percona-toolkit
    - percona-toolkit-configure

- ansible.builtin.import_tasks: scripts.yml
  tags:
    - configuration
    - percona-toolkit
    - percona-toolkit-scripts

- ansible.builtin.import_tasks: jobs.yml
  tags:
    - configuration
    - percona-toolkit
    - percona-toolkit-jobs
